namespace CtxApp.Api.Localization;

/// <summary>
/// Marker type for the API's user-facing messages: it names the resource set
/// <c>Resources/Messages.resx</c> (plus one <c>Messages.&lt;culture&gt;.resx</c>
/// per language), so an endpoint asks for <c>IStringLocalizer&lt;Messages&gt;</c>
/// and reads a message by key:
/// <code>
/// app.MapPost("/v1/example", (IStringLocalizer&lt;Messages&gt; loc) =&gt;
///     Results.BadRequest(new { error = loc["example.badRequest"].Value }));
/// </code>
/// Keys are namespaced by feature (<c>auth.</c>, <c>media.</c>, …). The strings
/// themselves are generated by ctx.0 from each feature's translation fragments;
/// an unknown key returns the key itself rather than throwing, which is how a
/// missing translation shows up in a response instead of taking the request down.
/// </summary>
public sealed class Messages
{
}
