import path from 'node:path';
import fs from 'fs-extra';
import { substitute } from './substitute.js';
import type { TemplateVars } from './types.js';

/**
 * The generated workspace `AGENTS.md` is a *derived* artifact: a static preamble
 * (from `templates/workspace/AGENTS.md`) followed by an engine-generated block
 * that documents the features enabled in this workspace. Each feature overlay
 * may contribute an `agents.md` fragment (alongside its `feature.json`); the
 * engine concatenates them, in the same deterministic order layers are applied,
 * into the block below. This mirrors how hierarchical context files are composed
 * rather than authored per repo — enabling a feature contributes its guidance,
 * disabling it removes it.
 *
 * The block is delimited by markers so a later `enable`/`disable` can regenerate
 * exactly this region, leaving the human-authored preamble untouched.
 */
export const AGENTS_BLOCK_START = '<!-- ctx:agents:features:start -->';
export const AGENTS_BLOCK_END = '<!-- ctx:agents:features:end -->';

/** The name of the per-overlay context fragment (engine metadata, never copied). */
export const AGENTS_FRAGMENT_FILE = 'agents.md';

/** Workspace-relative directory holding the generated per-feature docs. */
export const FEATURE_DOCS_DIR = 'docs/features';

/**
 * Workspace-relative path of a feature's dedicated doc, e.g. `auth` →
 * `docs/features/AUTH.md`. POSIX separators so it renders as a portable link in
 * the composed `AGENTS.md` regardless of host platform.
 */
export function featureDocPath(id: string): string {
  return `${FEATURE_DOCS_DIR}/${id.toUpperCase()}.md`;
}

/** One enabled feature's contribution to the composed `AGENTS.md`. */
export interface AgentsFragment {
  /** Feature id, e.g. "auth". */
  id: string;
  /** One-line summary from the feature manifest (section subtitle). */
  summary?: string;
  /** Markdown body from the overlay's `agents.md` (may be empty). */
  body: string;
}

/**
 * Read an overlay's `agents.md` fragment, applying token substitution. Returns
 * `undefined` when the overlay ships no fragment.
 */
export async function readAgentsFragment(
  overlayDir: string,
  vars: TemplateVars,
): Promise<string | undefined> {
  const p = path.join(overlayDir, AGENTS_FRAGMENT_FILE);
  if (!(await fs.pathExists(p))) return undefined;
  const raw = await fs.readFile(p, 'utf8');
  return substitute(raw, vars).trim();
}

/** Build the generated feature block (between the markers, inclusive). */
function renderFeatureBlock(fragments: AgentsFragment[]): string {
  const lines: string[] = [
    AGENTS_BLOCK_START,
    '',
    '## Enabled features',
    '',
    'The features enabled in this workspace, each with a link to its dedicated ' +
      'doc. This table is generated by ctx0 — do not hand-edit it; edit the feature ' +
      'overlay instead. Enabling or disabling a feature regenerates it and its doc.',
    '',
  ];

  if (fragments.length === 0) {
    lines.push('_No optional features are enabled._', '');
  } else {
    lines.push('| Feature | Docs |', '|---|---|');
    for (const f of fragments) {
      const feature = `${f.id}${f.summary ? ` — ${f.summary}` : ''}`;
      lines.push(`| ${feature} | \`${featureDocPath(f.id)}\` |`);
    }
    lines.push('');
  }

  lines.push(AGENTS_BLOCK_END);
  return lines.join('\n');
}

/**
 * Render a feature's dedicated doc file (`docs/features/<ID>.md`). The body is the
 * overlay's `agents.md` fragment(s), already token-substituted and (for two-sided
 * features) joined mobile-then-api. Wrapped with an H1 and a generated-file notice
 * so the standalone doc reads on its own and warns against hand-editing.
 */
export function renderFeatureDoc(fragment: AgentsFragment): string {
  const title = `# ${fragment.id}${fragment.summary ? ` — ${fragment.summary}` : ''}`;
  const notice =
    '<!-- Generated by ctx0 — do not hand-edit; edit the feature overlay’s ' +
    'agents.md instead. Disabling the feature removes this file. -->';
  const parts = [title, '', notice];
  if (fragment.body.trim()) parts.push('', fragment.body.trim());
  return `${parts.join('\n')}\n`;
}

/**
 * Compose the final `AGENTS.md` from a preamble and the enabled-feature
 * fragments. Idempotent: if the preamble already contains a generated block
 * (regeneration on enable/disable), it is replaced in place; otherwise the block
 * is appended. Running this twice with the same fragments yields the same file.
 */
export function composeAgentsDoc(preamble: string, fragments: AgentsFragment[]): string {
  const block = renderFeatureBlock(fragments);
  const startIdx = preamble.indexOf(AGENTS_BLOCK_START);

  const before =
    startIdx !== -1 ? preamble.slice(0, startIdx).trimEnd() : preamble.trimEnd();
  const head = before ? `${before}\n\n` : '';

  let tail = '';
  if (startIdx !== -1) {
    const endMarker = preamble.indexOf(AGENTS_BLOCK_END, startIdx);
    const after =
      endMarker !== -1 ? preamble.slice(endMarker + AGENTS_BLOCK_END.length) : '';
    const trimmed = after.replace(/^\s+/, '').trimEnd();
    if (trimmed) tail = `\n${trimmed}\n`;
  }

  return `${head}${block}\n${tail}`;
}
